// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqliteStore

import (
	"database/sql"
)

type StravaActivity struct {
	ID                 int64
	ActivityID         int64
	UserID             int64
	ActivityName       string
	Distance           float64
	MovingTime         int64
	ElapsedTime        int64
	TotalElevationGain float64
	ActivityType       string
	StartDate          string
	StartDateLocal     string
	Timezone           string
	AchievementCount   int64
	KudosCount         int64
	CommentCount       int64
	AthleteCount       int64
	PhotoCount         int64
	IsTrainer          bool
	IsCommute          bool
	IsManual           bool
	IsPrivate          bool
	IsFlagged          bool
	GearID             sql.NullInt64
	FromStrava         bool
}

type StravaAuthToken struct {
	ID           int64
	AthleteID    int64
	Firstname    string
	Lastname     sql.NullString
	RefreshToken string
	AccessToken  string
	ExpiresIn    int64
	ExpiresAt    int64
}

type StravaGear struct {
	ID        int64
	GearID    string
	UserID    int64
	Name      string
	Distance  float64
	IsPrimary bool
}

type User struct {
	ID              int64
	Username        string
	StravaAthleteID int64
}
